Controllers/Catalog1Controller.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ScladCRUD.Models;
using ScladCRUD.Models.ViewModel;
using System.Linq.Expressions;

namespace ScladCRUD.Controllers
{
    public class Catalog1Controller : Controller
    {
        private readonly ScladContext _context;
        public Catalog1Controller(ScladContext context)
        {
            _context = context;
        }

        // GET: Catalog1Controller
        public ActionResult Index(string searchBy, string searchValue)

        {
            var data = (from c in _context.Catalog1
                        join p in _context.Product1
                        on c.IdProduct equals p.IdProduct
                        select new ListViewModel
                        {
                            IdCatalog = c.IdCatalog,
                            ProductName= p.ProductName,
                            Articul= p.Articul,
                            Price =(p.Cost * p.Margin)/100,
                            Description=c.Description,
                            ProductPic= p.ProductPic


                        }).ToList();

            if (string.IsNullOrEmpty(searchValue))
            {
                TempData["InfoMessage"] = "Введите значение для поиска";
                return View(data);
            }
            else
            {
                if (searchBy.ToLower() == "productname")
                {
                    var searchByProductName = data.Where(p => p.ProductName.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductName);
                }
                else if (searchBy.ToLower() == "articul")
                {
                    var searchByProductArticul = data.Where(p => p.Articul.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductArticul);
                }
                else if (searchBy.ToLower() == "price")
                {
                    var searchByProductCost = data.Where(p => p.Price == int.Parse(searchValue));
                    return View(searchByProductCost);
                }
            }
            return View(data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            Catalog1 catalog = new Catalog1();

            return View(catalog);
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Catalog1 catalog)
        {
            _context.Add(catalog);
            _context.SaveChanges();
            TempData["AlertMessage"] = "Товар Создан!";
            return RedirectToAction("index");
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int id)
        {

            Catalog1 catalog = _context.Catalog1.Find(id);
            return View(catalog);
        }

        // POST: FacturaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Catalog1 catalog)
        {
            try
            {
                Catalog1 pr = _context.Catalog1.Find(catalog.IdCatalog);
                pr.IdCatalog = catalog.IdCatalog;
                pr.Description = catalog.Description;
                _context.SaveChanges();
                TempData["AlertMessage"] = "Товар изменен!";
                return RedirectToAction(nameof(Index));
            }
            catch
            {

                return View();
            }
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            _context.Catalog1.Remove(_context.Catalog1.Find(id));
            _context.SaveChanges();
            TempData["AlertMessage"] = "Товар удален!";
            return RedirectToAction(nameof(Index));
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.IdentityModel.Tokens;
using System.Security.Claims;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;


namespace ScladCRUD.Controllers
{/*
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    
    [ApiController]
    public class LoginController : ControllerBase
    {
        private readonly IConfiguration _config;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;

        public LoginController(IConfiguration config,SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _config = config;
            _signInManager = signInManager;
            _userManager = userManager;
        }
        
        

       

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Login([FromBody] LoginModel login)
        {
            var user = Authenticate(login.UserName, login.Password);
            if (user.Result != null)
            {
                var token = GenerateToken(login.UserName);
                return Ok(token);
            }
            return BadRequest("Login Failed");
            
        }
        private async Task <IdentityUser?> Authenticate (string userName, string Password)
        {
            var result = await _signInManager.PasswordSignInAsync(userName,Password,false,lockoutOnFailure: false);
            if (result.Succeeded)
            {
                var currentUser = await _userManager.FindByNameAsync(userName);
                if (currentUser != null)
                {
                    return currentUser;
                }
            }
            return null;
        }
        private string GenerateToken(string Username)
        {
            var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_config.GetSection("Jwt:Key").Value));
            var credentials = new SigningCredentials(securityKey,SecurityAlgorithms.HmacSha256);
            var claims = new[]
            {
             new Claim(ClaimTypes.NameIdentifier, Username)
            };
            var token = new JwtSecurityToken(
                _config.GetSection("Jwt:Issuer").Value , _config.GetSection("Jwt:Audience").Value,
                claims,
                expires: DateTime.Now.AddMinutes(15),
                signingCredentials: credentials);
            return new JwtSecurityTokenHandler().WriteToken(token);
        }

        [HttpGet]
        public IActionResult Test()
        {
            return Ok("Token ydacno sozdan");
        }
    }*/
}

Controllers/Product1Controller.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using ScladCRUD.Models;

namespace ScladCRUD.Controllers
{
    public class Product1Controller : Controller
    {
        private readonly ScladContext _context;
        public Product1Controller(ScladContext context)
        {
            _context = context;
        }
        // GET: Product1Controller
        public ActionResult Index(string searchBy, string searchValue)
        {
            List<Product1> products;
            products = _context.Product1.ToList();
            if (string.IsNullOrEmpty(searchValue))
            {
                TempData["InfoMessage"] = "Введите значение для поиска";
                return View(products);
            }
            else
            {
                if(searchBy.ToLower() == "productname")
                {
                    var searchByProductName = products.Where(p => p.ProductName.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductName);
                }
                else if (searchBy.ToLower() == "articul")
                {
                    var searchByProductArticul = products.Where(p => p.Articul.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductArticul);
                }
                else if (searchBy.ToLower() == "cost")
                {
                    var searchByProductCost = products.Where(p => p.Cost==int.Parse(searchValue));
                    return View(searchByProductCost);
                }
            }
            return View(products);
        }

        // GET: Product1Controller/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductController/Create
        [HttpGet]
        public IActionResult Create()
        {
            Product1 product = new Product1();

            return View(product);
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Product1 product)
        {
            _context.Add(product);
            _context.SaveChanges();
            TempData["AlertMessage"] = "Продукт Создан!";
            return RedirectToAction("index");
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int id)
        {

            Product1 product = _context.Product1.Find(id);
            return View(product);
        }

        // POST: FacturaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product1 product)
        {
            try
            {
                Product1 pr = _context.Product1.Find(product.IdProduct);
                pr.IdProduct = product.IdProduct;
                pr.ProductName = product.ProductName;
                pr.Articul = product.Articul;
                pr.Cost = product.Cost;
                pr.ProductPic = product.ProductPic;
                pr.Margin = product.Margin;
                _context.SaveChanges();
                TempData["AlertMessage"] = "Продукт изменен!";
                return RedirectToAction(nameof(Index));
            }
            catch
            {

                return View();
            }
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            _context.Product1.Remove(_context.Product1.Find(id));
            _context.SaveChanges();
            TempData["AlertMessage"] = "Продукт удален!";
            return RedirectToAction(nameof(Index));
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/RegisterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ScladCRUD.Controllers
{
    
    [ApiController]
    public class RegisterController : ControllerBase
    {/*
        private readonly UserManager<IdentityUser> _userManager;

        public RegisterController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task <ActionResult> Register (string userName,  string Password)
        {
            IdentityUser user = new IdentityUser(userName);
            var result = await _userManager.CreateAsync(user,Password);
            if (result.Succeeded)
            {
                return Ok("Регистрация успешна!");
           
            }
            return BadRequest("Регистрация не произошла!");
        }*/
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ScladCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ScladCRUD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-transparent border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/image4.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">На главную</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product1" asp-action="Index">Продукты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog1" asp-action="Index">Каталог товаров</a>
                        </li>
                        <tab> <tab> <tab>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Register">Регистрация</a>
                         </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Вход в аккаунт</a>
                         </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ScladCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/site.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>